# Generated by Django 4.1.4 on 2022-12-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='creat_date',
            new_name='created_date',
        ),
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
