# Generated by Django 4.1.4 on 2022-12-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_creat_date_post_created_date_post_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='./image'),
        ),
    ]
